$(function(){
    //alert("dddd");
    $("#hide").click(function(){
        $("#k1").hide(2000,function(){
            $("#k2").html("koniec");
        });
    });
    $("#show").click(function(){
        $("#k1").show(2000,function(){
            $("#k2").html("pokazano");
        });
    });
    $("#toggle").click(function(){
        $("#k1").toggle("slow");
    });

    $("#fadeOut").click(function(){
        $("#k1").fadeOut(2000);
    });
    $("#fadeIn").click(function(){
        $("#k1").fadeIn(2000);
    });
    $("#fadeTo").click(function(){
        $("#k1").fadeTo(2000,0);
    });
    $("#fadeToggle").click(function(){
        $("#k1").fadeToggle();
    });
    $("#slideUp").click(function(){
        $("#k1").slideUp(4000);
    });
    $("#slideDown").click(function(){
        $("#k1").slideDown(4000);
    });
});